'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.239
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.Ind
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ExceptionPrompts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LyriX.ExceptionPrompts", GetType(ExceptionPrompts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 集合是只读的。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property CollectionReadOnly() As String
            Get
                Return ResourceManager.GetString("CollectionReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的类型没有实现 {0} 接口。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InterfaceUnimplemented() As String
            Get
                Return ResourceManager.GetString("InterfaceUnimplemented", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的类型没有继承自 {0}。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidBaseClass() As String
            Get
                Return ResourceManager.GetString("InvalidBaseClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 必须指定一个四位数年份。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidgYear() As String
            Get
                Return ResourceManager.GetString("InvalidgYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的对象实例的类型不是 {0} 或是其派生类型。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidInstanceType() As String
            Get
                Return ResourceManager.GetString("InvalidInstanceType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Xml 文档 {0} 格式不正确。
        '''{1} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property InvalidXmlDocument() As String
            Get
                Return ResourceManager.GetString("InvalidXmlDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 索引号已全部分配完毕。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NoIndexAvaliable() As String
            Get
                Return ResourceManager.GetString("NoIndexAvaliable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 必须指定一个非负数。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NonNegative() As String
            Get
                Return ResourceManager.GetString("NonNegative", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的项目“{0}”不是 {1} 的元素。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NotInList() As String
            Get
                Return ResourceManager.GetString("NotInList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 对象是只读的。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ObjectReadOnly() As String
            Get
                Return ResourceManager.GetString("ObjectReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的元素已经是另一个元素的逻辑子元素。请先将其断开连接。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ParentAlreadyExists() As String
            Get
                Return ResourceManager.GetString("ParentAlreadyExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 指定的歌词版本不在当前歌词的版本列表中。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property VersionNotInList() As String
            Get
                Return ResourceManager.GetString("VersionNotInList", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
