'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.239
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources.User
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Prompts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DocumentViewModel.Prompts", GetType(Prompts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 所有文件 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AllFiles() As String
            Get
                Return ResourceManager.GetString("AllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 所有支持的文档 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property AllSupportedDocuments() As String
            Get
                Return ResourceManager.GetString("AllSupportedDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 取消 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文档当前的读写上下文。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DDocIOContext() As String
            Get
                Return ResourceManager.GetString("DDocIOContext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 表示文档是否是只读的。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DDocReadOnly() As String
            Get
                Return ResourceManager.GetString("DDocReadOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 文档的标题。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DDocTitle() As String
            Get
                Return ResourceManager.GetString("DDocTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 总共有 {0:d} 个文档。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DocumentCount() As String
            Get
                Return ResourceManager.GetString("DocumentCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 总共有 {0:d} 个文档，其中在列表显示了 {1:d} 个。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property DocumentCountEx() As String
            Get
                Return ResourceManager.GetString("DocumentCountEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IO 上下文 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property IOContext() As String
            Get
                Return ResourceManager.GetString("IOContext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 已修改 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Modified() As String
            Get
                Return ResourceManager.GetString("Modified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 名称 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 新建文档 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NewDocument() As String
            Get
                Return ResourceManager.GetString("NewDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 否 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 否(&amp;N) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NoButton() As String
            Get
                Return ResourceManager.GetString("NoButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 没有文档。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NoDocument() As String
            Get
                Return ResourceManager.GetString("NoDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正常 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 总共有 {0:d} 个文档，但在列表中没有文档被显示。 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property NoVisibleDocument() As String
            Get
                Return ResourceManager.GetString("NoVisibleDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 从 {0} 中打开 {1} 时
        '''发生了错误：
        '''{2} 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property OpenDocumentError() As String
            Get
                Return ResourceManager.GetString("OpenDocumentError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 重试(&amp;R) 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property RetryButton() As String
            Get
                Return ResourceManager.GetString("RetryButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在重试 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Retrying() As String
            Get
                Return ResourceManager.GetString("Retrying", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 是否保存对 {0} 的修改？ 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SaveDocument() As String
            Get
                Return ResourceManager.GetString("SaveDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 是否保存对以下 {0:d} 个文档的修改： 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property SaveDocumentCount() As String
            Get
                Return ResourceManager.GetString("SaveDocumentCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 正在保存 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Saving() As String
            Get
                Return ResourceManager.GetString("Saving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 状态 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 类型 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 视图数量 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property ViewCount() As String
            Get
                Return ResourceManager.GetString("ViewCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 是 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
